GET http://localhost:5000/produtos

###
POST http://localhost:5000/produtos
Content-Type: application/json

{
  "nome": "martelo",
  "marca": "stel",
  "modelo": "profissional",
  "preco": 30,
  "caracteristicas": {
    "tipo_material": "aço",
    "tamanho": "M",
    "tensao": "10v"
  }
}

###
GET http://localhost:5000/produtos/9

###
PUT http://localhost:5000/produtos/9 HTTP/1.1
Content-Type: application/json

{
  "nome": "martelo de thor",
  "marca": "valhala",
  "modelo": "divino",
  "preco": 999999,
  "caracteristicas": {
    "tipo_material": "aço infernal",
    "tamanho": "DD",
    "tensao": "99999v"
  }
}

###
DELETE http://localhost:5000/produtos/9 HTTP/1.1
