GET http://localhost:5000/produtos

###
POST http://localhost:5000/produtos
Content-Type: application/json

{
  "nome": "martelo",
  "marca": "stel",
  "modelo": "profissional",
  "preco": 30,
  "caracteristicas": {
    "tipo_material": "aço",
    "tamanho": "M",
    "tensao": "10v"
  }
}

###
GET http://localhost:5000/produtos/5
